### ISSUE TITLE
bevy 0.6 break

### ISSUE THREAD

**Issue by pyweeker** [jonathanrlouie/tanks#1]
hello, your example game is interessant to study for beginners like me, could you please fix it to run with bevy 0.6 ?

**Comment by jonathanrlouie** [comment]
@pyweeker Hey, sure, I can take a look at it. I think I can probably update it by this weekend.

**Comment by jonathanrlouie** [comment]
@pyweeker I've updated the example to work with Bevy 0.6.0 now.

**Comment by pyweeker** [comment]
thank you jonathan, i'll try to extend it .

Le lun. 17 janv. 2022 à 09:58, jonathanrlouie ***@***.***> a
écrit :
